name: info's @ disposable-mailbox.eu 
markdown: kramdown
highlighter: rouge # pygments or rouge or nullexclude: ["node_modules", "gulpfile.js", "package.json"]
exclude: ["node_modules", "gulpfile.js", "package.json"]
#permalink: /:year/:month/:day/:title:output_ext
themecolor: yellow # blue, blue2, yellow  orange green grey purple OR red
